'Boiled egg',
'White cheese',
'Jam + butter',
'Bread (brown –white)',
'Milk (Regular - low fat)',
'Fruit',
'Water',
'Foul medames with tomato',
'Wedge cheese',
'honey + Labna',
'Juice',
'Chicken creamy soup',
'Italian grilled chicken',
'Sautéed vegetables',
'White rice',
'Italian green salade with toasted bread',
'vermicelli soup',
'Lasagna with meet',
'Vegetable rice',
'Hummus',
'Orzo soup',
'chicken kofta with sauce',
'steamed broccoli',
'Bokhari rice',
'Green salade',
'Dessert',
'carrot soup',
'Chicken chops with sauce',
'Haba haba rice',
'Labnah Sandwich',
'Water +Juice',
'Corn flakes + omelette with dill',
'Slice cheese',
'halawa + Labna',
'Shakshuka',
'Jam + honey',
'harrira soup',
'Baked fish with tahena',
'Sayadiyah rice',
'Mixed vegetables idam',
'Tahini salade',
'pumpkin soup',
'rice (yellow)',
'Beet root salade',
'oatssoup',
'Shish tawok',
'Green beansidam',
'Dogus',
'Vegetable creamysoup',
'chicken tandoori',
'Mandi rice',
'Spinach Croissant Pie',
'Water +Tea',
'Scramble egg with mushrooms',
'lentil',
'Labna + honey',
'vegetable soup',
'Lamb biryani',
'Bamya sutee',
'Biryani Rice',
'Motable',
'lentil soup',
'broasted chicken',
'Vermicelli rice',
'Greek salad',
'chicken noodles soup',
'Chicken shawerma',
'Potatoidam',
'Cheese Sandwich',
'Water + Juice',
'Hot dog slices with vegetables',
'Boiled egg +pancake',
'Jam+ butter',
'oven roasted fish',
'cowpea edam',
'Rice with nuts',
'Fatush salade with pomegrante',
'ChickenKofta',
'Kabsa rice',
'Pumpkin soup',
'Macaroni spaghiti with sauce',
'Tabboula',
'Vermicelli soup',
'Zaater Croissant Pie',
'Water + Tea',
'Foul medames Lebanese style',
'Egg with vegetables',
'Carrot soup',
'Lamb stew with okra',
'Courgettes edam',
'Mixed bean salad',
'chicken biryani',
'Cucmber labn salade',
'harira soup',
'Mandi chicken',
'Molokhia',
'Lentil Soup',
'Tuna sandwich',
'Seasoned lentil',
'Scramble egg',
'butter + Jam',
'Grilled chicken with tomato',
'Mixed vegetable casserole',
'Macaroni with vegetables and garlic',
'Baked chicken with vegetables',
'Arugula salade',
'Jareesh Soup',
'chicken breast',
'Grean peas idam',
'Vegetable soup',
'Grilled chicken',
'Chicken Croissant Pie',
'Hamsa tuna with',
'butter+ Jam',
'Oats soup',
'Okra casserole',
'Baked potato wedges',
'Cauliflower Edam',
'Chicken Kofta with Tomato Sauce',
'Egg Sandwich',
'Beans in the oven',
'Mosaga',
'bachamel',
'Chicken lemon sauce',
'Tabola',
'Chicken kofta with sauce',
'White Rise',
'labnah sandwich',
'Corn flakes+ tamiya',
'Risoni Soup',
'grilledfish',
'Labna ( skimmed-low fat )',
'Margog',
'Marrow with carrot idam',
'Spaghetti',
'Chicken with cream and mushroom',
'Fried potato +corn with butter',
'cheese sandwish',
'LAMB CHOP BBQ',
'courgettes edam',
'Laban (Regular - low fat)',
'shish kebab',
'Lamb liver',
'nuts rice',
'Mutabal',
'Greensalade with onion',
'Creamy corn soup',
'white cheese',
'boiled eggs',
'slice cheese',
'barley soup',
'Grilled meat Kofta',
'Grilled Chicken',
'mixed vegetables',
'chicken mandi',
'Spinach with lentil',
'Arugula Salad',
'laban',
'Tahina Salad',
'Yogurt',
'Chickenshawerma',
'Rice with vermicelli',