[
  {
    id: 154,
    category: "A",
    mealID: 26,
    name: "Boiled egg",
    name2l: "بيض مسلوق ",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 155,
    category: "A",
    mealID: 189,
    name: "White cheese",
    name2l: "جبنة بيضاء",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 156,
    category: "A",
    mealID: 108,
    name: "Jam  + butter ",
    name2l: "مربى+زبدة",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 157,
    category: "A",
    mealID: 32,
    name: "Bread (brown –white)",
    name2l: "خبز",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 158,
    category: "A",
    mealID: 133,
    name: "Milk (Regular - low fat)",
    name2l: "حليب",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 159,
    category: "A",
    mealID: 3,
    name: "Fruit",
    name2l: "فاكهة",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 160,
    category: "A",
    mealID: 186,
    name: "Water ",
    name2l: "ماء",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 161,
    category: "B",
    mealID: 72,
    name: "Foul medames with tomato",
    name2l: "فول مدمس بالطماطم",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 162,
    category: "B",
    mealID: 187,
    name: "Wedge cheese",
    name2l: "جبن مثلثات",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 163,
    category: "B",
    mealID: 98,
    name: "Honey + Labna",
    name2l: "لبنة+عسل",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 164,
    category: "B",
    mealID: 32,
    name: "Bread (brown –white)",
    name2l: "خبز",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 165,
    category: "B",
    mealID: 133,
    name: "Milk (Regular - low fat)",
    name2l: "حليب",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 166,
    category: "B",
    mealID: 5,
    name: "Juice",
    name2l: "فاكهة",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 167,
    category: "B",
    mealID: 186,
    name: "Water ",
    name2l: "ماء",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
];
