[
  {
    id: 1,
    category: "A",
    mealID: 103,
    name: "Hummus",
    name2l: "سلطة حمص",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 3,
    category: "A",
    mealID: 104,
    name: "Hummus",
    name2l: "حمص",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 4,
    category: "A",
    mealID: 105,
    name: "Italian green salade with toasted bread",
    name2l: "سلطة خضراء مع الخبز المحمص بالتتبيلة الايطالية",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 5,
    category: "A",
    mealID: 105,
    name: "Italian green salade with toasted bread",
    name2l: "سلطة خضراء مع الخبز المحمص بالتتبيلة الايطالية",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 6,
    category: "B",
    mealID: 7,
    name: "Bachamel",
    name2l: "مكرونة بالباشميل",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 7,
    category: "B",
    mealID: 14,
    name: "Arugula Salad",
    name2l: "سلطة جرجير",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 8,
    category: "B",
    mealID: 18,
    name: "Baked fish with tahena",
    name2l: "سمك بالطحينية بالفرن",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 36,
    category: "A",
    mealID: 144,
    name: "Oats  soup",
    name2l: "شوربة شوفان",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 82,
    category: "A",
    mealID: 103,
    name: "Hummus",
    name2l: "سلطة حمص",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 101,
    category: "A",
    mealID: 3,
    name: "Fruit",
    name2l: "فاكهة",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 102,
    category: "A",
    mealID: 5,
    name: "Juice",
    name2l: "فاكهة",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 103,
    category: "A",
    mealID: 9,
    name: "Grilled   chicken",
    name2l: "دجاج مشوي",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 104,
    category: "A",
    mealID: 10,
    name: "Halawa + Labna ",
    name2l: "حلاوة طحينية+لبنة",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
  {
    id: 105,
    category: "A",
    mealID: 15,
    name: "Arugula salade",
    name2l: "سلطة جرجير",
    mealTime: "Breakfast",
    mealDay: "Sunday",
    mealWeek: "1",
  },
];
